from __future__ import annotations

from typing import Any

from .schema import make_error

ALLOWED_COMMANDS = frozenset(
    {
        "status",
        "capabilities",
        "latest",
        "audit_tail",
        "permissions.prime",
        "helper.ping",
        "queue.list",
        "queue.append",
        "codex.frontmost",
        "codex.windows",
        "codex.threads",
        "codex.thread_map",
        "codex.focus",
        "codex.select_thread",
        "codex.send_visible_message",
        "codex.continue_thread",
        "codex.snapshot",
        "codex.inspect",
        "codex.ax_tree",
        "codex.connections.status",
        "codex.app_server.status",
        "codex.app_server.threads",
        "codex.app_server.loaded_threads",
        "codex.app_server.subscribe",
        "codex.app_server.remote_control_status",
        "customer_mac.status",
        "customer_mac.capabilities",
        "customer_mac.control_status",
        "customer_mac.control_start",
        "customer_mac.control_stop",
        "customer_mac.control_kill_switch",
        "customer_mac.desktop_see",
        "customer_mac.desktop_click",
        "customer_mac.desktop_type",
        "customer_mac.desktop_scroll",
        "customer_mac.desktop_drag",
        "customer_mac.desktop_hotkey",
        "customer_mac.desktop_focus_app",
        "customer_mac.desktop_window",
        "customer_mac.desktop_menu",
        "customer_mac.desktop_browser_action",
        "customer_mac.snapshot",
        "customer_mac.ax_tree",
        "customer_mac.app_focus",
        "customer_mac.local_site_open",
        "customer_mac.local_site_action",
        "customer_mac.iphone_mirroring_status",
        "customer_mac.iphone_see",
        "customer_mac.iphone_tap",
        "customer_mac.iphone_swipe",
        "customer_mac.iphone_type",
        "customer_mac.iphone_mirroring_focus",
        "customer_mac.iphone_mirroring_home",
        "customer_mac.iphone_mirroring_app_switcher",
        "customer_mac.iphone_mirroring_spotlight",
        "customer_mac.iphone_mirroring_type_spotlight",
        "customer_mac.iphone_mirroring_open_app",
        "customer_mac.iphone_mirroring_tap_named_target",
        "customer_mac.iphone_mirroring_scroll",
        "customer_mac.iphone_mirroring_swipe_left",
        "customer_mac.iphone_mirroring_swipe_right",
        "customer_mac.iphone_mirroring_swipe_up",
        "customer_mac.iphone_mirroring_swipe_down",
        "customer_mac.iphone_mirroring_type_approved_text",
        "customer_mac.iphone_mirroring_send_approved_message",
        "customer_mac.screen_sharing_status",
    }
)

COMMAND_METADATA: dict[str, dict[str, Any]] = {
    "status": {"mode": "read_only", "source": "process", "requires_permission": []},
    "capabilities": {"mode": "read_only", "source": "policy", "requires_permission": []},
    "latest": {"mode": "read_only", "source": "state", "requires_permission": []},
    "audit_tail": {"mode": "read_only", "source": "audit", "requires_permission": []},
    "permissions.prime": {"mode": "read_only", "source": "macos_tcc_prompt", "requires_permission": []},
    "helper.ping": {"mode": "read_only", "source": "computer_use_helper", "requires_permission": []},
    "queue.list": {"mode": "read_only", "source": "queue", "requires_permission": []},
    "queue.append": {"mode": "read_only", "source": "queue", "requires_permission": []},
    "codex.frontmost": {"mode": "read_only", "source": "ax", "requires_permission": ["accessibility"]},
    "codex.windows": {"mode": "read_only", "source": "ax", "requires_permission": ["accessibility"]},
    "codex.threads": {"mode": "read_only", "source": "ax", "requires_permission": ["accessibility"]},
    "codex.thread_map": {"mode": "read_only", "source": "ax_app_server", "requires_permission": ["accessibility"]},
    "codex.focus": {"mode": "guarded_visible_action", "source": "ax", "requires_permission": ["accessibility"]},
    "codex.select_thread": {"mode": "guarded_visible_action", "source": "ax", "requires_permission": ["accessibility"]},
    "codex.send_visible_message": {"mode": "guarded_visible_message_action", "source": "codex_visible_gui", "requires_permission": ["accessibility"], "requires_approval": True, "prompt_scope": "approved_message"},
    "codex.continue_thread": {"mode": "support_canary_guarded_visible_action", "source": "ax", "requires_permission": ["accessibility"], "requires_approval": True, "support_only": True, "prompt_scope": "exact_continue_only"},
    "codex.snapshot": {"mode": "read_only", "source": "screenshot", "requires_permission": ["screen_recording"]},
    "codex.inspect": {"mode": "read_only", "source": "ax", "requires_permission": ["accessibility"]},
    "codex.ax_tree": {"mode": "read_only", "source": "ax", "requires_permission": ["accessibility"]},
    "codex.connections.status": {"mode": "read_only", "source": "app_server", "requires_permission": []},
    "codex.app_server.status": {"mode": "read_only", "source": "app_server", "requires_permission": []},
    "codex.app_server.threads": {"mode": "read_only", "source": "app_server", "requires_permission": []},
    "codex.app_server.loaded_threads": {"mode": "read_only", "source": "app_server", "requires_permission": []},
    "codex.app_server.subscribe": {"mode": "read_only", "source": "app_server", "requires_permission": []},
    "codex.app_server.remote_control_status": {"mode": "read_only", "source": "codex_native_remote_control", "requires_permission": []},
    "customer_mac.status": {"mode": "read_only", "source": "macos", "requires_permission": []},
    "customer_mac.capabilities": {"mode": "read_only", "source": "policy", "requires_permission": []},
    "customer_mac.control_status": {"mode": "read_only", "source": "control_session", "requires_permission": []},
    "customer_mac.control_start": {"mode": "control_session", "source": "customer_grant", "requires_permission": [], "starts_live_control": True},
    "customer_mac.control_stop": {"mode": "control_session", "source": "customer_grant", "requires_permission": [], "stops_live_control": True},
    "customer_mac.control_kill_switch": {"mode": "control_session", "source": "customer_grant", "requires_permission": [], "blocks_live_control": True},
    "customer_mac.desktop_see": {"mode": "read_only", "source": "peekaboo_or_screen_ax", "requires_permission": ["screen_recording", "accessibility"], "sensitive_app_block": True},
    "customer_mac.desktop_click": {"mode": "full_access_control", "source": "peekaboo_or_ax_quartz", "requires_permission": ["accessibility"], "requires_active_control_session": True},
    "customer_mac.desktop_type": {"mode": "full_access_control", "source": "peekaboo_or_system_events", "requires_permission": ["accessibility"], "requires_active_control_session": True, "high_impact_in_ask_permission": True},
    "customer_mac.desktop_scroll": {"mode": "full_access_control", "source": "peekaboo_or_quartz", "requires_permission": ["accessibility"], "requires_active_control_session": True},
    "customer_mac.desktop_drag": {"mode": "full_access_control", "source": "peekaboo_or_quartz", "requires_permission": ["accessibility"], "requires_active_control_session": True},
    "customer_mac.desktop_hotkey": {"mode": "full_access_control", "source": "peekaboo_or_system_events", "requires_permission": ["accessibility"], "requires_active_control_session": True},
    "customer_mac.desktop_focus_app": {"mode": "full_access_control", "source": "peekaboo_or_macos_open", "requires_permission": [], "requires_active_control_session": True},
    "customer_mac.desktop_window": {"mode": "full_access_control", "source": "peekaboo_or_system_events", "requires_permission": ["accessibility"], "requires_active_control_session": True},
    "customer_mac.desktop_menu": {"mode": "full_access_control", "source": "peekaboo", "requires_permission": ["accessibility"], "requires_active_control_session": True},
    "customer_mac.desktop_browser_action": {"mode": "full_access_control", "source": "browser_keyboard", "requires_permission": ["accessibility"], "requires_active_control_session": True},
    "customer_mac.snapshot": {"mode": "read_only", "source": "screenshot", "requires_permission": ["screen_recording"], "sensitive_app_block": True},
    "customer_mac.ax_tree": {"mode": "read_only", "source": "ax", "requires_permission": ["accessibility"], "sensitive_app_block": True},
    "customer_mac.app_focus": {"mode": "guarded_visible_action", "source": "macos_open", "requires_permission": [], "requires_approval": True, "sensitive_app_block": True},
    "customer_mac.local_site_open": {"mode": "guarded_visible_action", "source": "macos_open", "requires_permission": [], "requires_approval": True, "url_scope": "localhost_loopback_local"},
    "customer_mac.local_site_action": {"mode": "guarded_visible_action", "source": "browser_keyboard", "requires_permission": ["accessibility"], "requires_approval": True, "allowlist": ["reload", "back", "forward"]},
    "customer_mac.iphone_mirroring_status": {"mode": "read_only", "source": "macos", "requires_permission": []},
    "customer_mac.iphone_see": {"mode": "read_only", "source": "peekaboo_or_screen_ax", "requires_permission": ["screen_recording", "accessibility"], "requires_frontmost_iphone_mirroring": True},
    "customer_mac.iphone_tap": {"mode": "full_access_control", "source": "peekaboo_or_ax_quartz", "requires_permission": ["accessibility"], "requires_active_control_session": True},
    "customer_mac.iphone_swipe": {"mode": "full_access_control", "source": "iphone_mirroring_quartz", "requires_permission": ["accessibility"], "requires_active_control_session": True},
    "customer_mac.iphone_type": {"mode": "full_access_control", "source": "peekaboo_or_system_events", "requires_permission": ["accessibility"], "requires_active_control_session": True, "high_impact_in_ask_permission": True},
    "customer_mac.iphone_mirroring_focus": {"mode": "full_access_control", "source": "macos_open", "requires_permission": [], "requires_active_control_session": True},
    "customer_mac.iphone_mirroring_home": {"mode": "full_access_control", "source": "iphone_mirroring_keyboard", "requires_permission": ["accessibility"], "requires_active_control_session": True},
    "customer_mac.iphone_mirroring_app_switcher": {"mode": "full_access_control", "source": "iphone_mirroring_keyboard", "requires_permission": ["accessibility"], "requires_active_control_session": True},
    "customer_mac.iphone_mirroring_spotlight": {"mode": "full_access_control", "source": "iphone_mirroring_keyboard", "requires_permission": ["accessibility"], "requires_active_control_session": True},
    "customer_mac.iphone_mirroring_type_spotlight": {"mode": "full_access_control", "source": "iphone_mirroring_keyboard", "requires_permission": ["accessibility"], "requires_active_control_session": True, "text_scope": "short_disposable_search_text"},
    "customer_mac.iphone_mirroring_open_app": {"mode": "full_access_control", "source": "iphone_mirroring_keyboard", "requires_permission": ["accessibility"], "requires_active_control_session": True},
    "customer_mac.iphone_mirroring_tap_named_target": {"mode": "full_access_control", "source": "iphone_mirroring_ax", "requires_permission": ["accessibility"], "requires_active_control_session": True},
    "customer_mac.iphone_mirroring_scroll": {"mode": "full_access_control", "source": "iphone_mirroring_quartz", "requires_permission": ["accessibility"], "requires_active_control_session": True},
    "customer_mac.iphone_mirroring_swipe_left": {"mode": "full_access_control", "source": "iphone_mirroring_quartz", "requires_permission": ["accessibility"], "requires_active_control_session": True, "high_impact_in_ask_permission": True},
    "customer_mac.iphone_mirroring_swipe_right": {"mode": "full_access_control", "source": "iphone_mirroring_quartz", "requires_permission": ["accessibility"], "requires_active_control_session": True, "high_impact_in_ask_permission": True},
    "customer_mac.iphone_mirroring_swipe_up": {"mode": "full_access_control", "source": "iphone_mirroring_quartz", "requires_permission": ["accessibility"], "requires_active_control_session": True, "high_impact_in_ask_permission": True},
    "customer_mac.iphone_mirroring_swipe_down": {"mode": "full_access_control", "source": "iphone_mirroring_quartz", "requires_permission": ["accessibility"], "requires_active_control_session": True, "high_impact_in_ask_permission": True},
    "customer_mac.iphone_mirroring_type_approved_text": {"mode": "full_access_control", "source": "iphone_mirroring_keyboard", "requires_permission": ["accessibility"], "requires_active_control_session": True, "high_impact_in_ask_permission": True},
    "customer_mac.iphone_mirroring_send_approved_message": {"mode": "full_access_control", "source": "iphone_mirroring_ax", "requires_permission": ["accessibility"], "requires_active_control_session": True, "high_impact_in_ask_permission": True},
    "customer_mac.screen_sharing_status": {"mode": "read_only", "source": "launchctl_lsof", "requires_permission": [], "bridge_can_enable": False},
}


class PolicyError(RuntimeError):
    def __init__(self, command: str) -> None:
        self.command = command
        self.error: dict[str, Any] = make_error(
            code="command_not_allowed",
            message=f"Command '{command}' is outside the Desktop Bridge MVP allowlist.",
            guidance="Use one of the allowlisted bridge commands. Run evaos-desktop-bridge capabilities --json for the current surface.",
        )
        super().__init__(self.error["message"])


def ensure_allowed(command: str) -> str:
    if command not in ALLOWED_COMMANDS:
        raise PolicyError(command)
    return command


def command_metadata(command: str) -> dict[str, Any]:
    ensure_allowed(command)
    return dict(COMMAND_METADATA[command])
